CREATE TABLE CATEGORIES
(
    CAT_ID          VARCHAR(20)  NOT NULL,
    CAT_RU          VARCHAR(50)  NOT NULL,
    CAT_DESCRIPTION TEXT         NOT NULL,
    CAT_KEYWORDS    VARCHAR(255) NOT NULL,
    CONSTRAINT CAT_PK PRIMARY KEY (CAT_ID)
);

CREATE TABLE ITEMS
(
    ITEM_ID          VARCHAR(20)   NOT NULL,
    ITEM_RU          VARCHAR(100)  NOT NULL,
    ITEM_DESCRIPTION VARCHAR(1000) NOT NULL,
    ITEM_KEYWORDS    VARCHAR(255)  NOT NULL,
    CAT_ID           VARCHAR(20)   NOT NULL,
    ITEM_FIRST_PAGE  BOOLEAN       NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID),
    CONSTRAINT ITEMS_CAT_ID_FK FOREIGN KEY (CAT_ID) REFERENCES CATEGORIES (CAT_ID)
);

CREATE TABLE CATEGORIES_ITEMS
(
    CATEGORIES_CAT_ID VARCHAR(20) NOT NULL,
    ITEMS_ITEM_ID     VARCHAR(20) NOT NULL,
    CONSTRAINT CAT_ITEM_PK PRIMARY KEY (CATEGORIES_CAT_ID, ITEMS_ITEM_ID),
    CONSTRAINT CATEGORIES_ITEMS_CAT_ID_FK FOREIGN KEY (CATEGORIES_CAT_ID) REFERENCES CATEGORIES (CAT_ID),
    CONSTRAINT CATEGORIES_ITEMS_ITEM_ID_FK FOREIGN KEY (ITEMS_ITEM_ID) REFERENCES ITEMS (ITEM_ID)
);